# Generated by Django 3.0.5 on 2023-05-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_ambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('Test', models.CharField(choices=[('blood glucose test', 'blood glucose test'), ('calcium test', 'calcium test'), ('cardiac enzymes', 'cardiac enzymes'), ('cholesterol and lipid tests', 'cholesterol and lipid tests'), ('CRP test', 'CRP test'), ('hba1c test', 'hba1c test')], default='blood glucose test', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
